// Cybersecurity categories — used in CategoryCard, SearchPage filters, and HomePage grid
// icon: matches a key in the CATEGORY_ICONS map inside CategoryCard.jsx
export const CATEGORIES = [
  {
    id: 1,
    name: "Web Security",
    slug: "web-security",
    description: "Tools for testing web application vulnerabilities, XSS, CSRF, SQLi, and more.",
    icon: "globe",
    color: "neon-blue",
    count: 3,
    tags: ["OWASP", "Bug Bounty", "Web App"],
  },
  {
    id: 2,
    name: "Network Security",
    slug: "network-security",
    description: "Scanners, sniffers, and IDS tools to secure and analyze network infrastructure.",
    icon: "wifi",
    color: "neon-green",
    count: 3,
    tags: ["IDS", "IPS", "Packet Analysis"],
  },
  {
    id: 3,
    name: "OSINT",
    slug: "osint",
    description: "Open-source intelligence tools for passive reconnaissance and information gathering.",
    icon: "eye",
    color: "neon-purple",
    count: 4,
    tags: ["Reconnaissance", "Passive", "Social Media"],
  },
  {
    id: 4,
    name: "Penetration Testing",
    slug: "penetration-testing",
    description: "Full-featured frameworks and tools for ethical hacking and red team operations.",
    icon: "shield",
    color: "neon-blue",
    count: 3,
    tags: ["Red Team", "Exploit", "Post-Exploitation"],
  },
  {
    id: 5,
    name: "Password Cracking",
    slug: "password-cracking",
    description: "GPU-accelerated and dictionary-based tools for password auditing and recovery.",
    icon: "lock",
    color: "neon-pink",
    count: 3,
    tags: ["Brute Force", "Hash", "Dictionary"],
  },
  {
    id: 6,
    name: "Reverse Engineering",
    slug: "reverse-engineering",
    description: "Disassemblers, decompilers, and debuggers to analyze binaries and malware.",
    icon: "code",
    color: "neon-green",
    count: 1,
    tags: ["Binary", "Malware", "CTF"],
  },
  {
    id: 7,
    name: "Digital Forensics",
    slug: "digital-forensics",
    description: "Forensic platforms and memory analysis tools for incident response.",
    icon: "database",
    color: "neon-purple",
    count: 2,
    tags: ["Evidence", "Memory", "Incident Response"],
  },
  {
    id: 8,
    name: "Malware Analysis",
    slug: "malware-analysis",
    description: "Sandbox environments and pattern matching tools for analyzing malicious code.",
    icon: "alert",
    color: "neon-pink",
    count: 2,
    tags: ["Sandbox", "Behavior", "Signatures"],
  },
  {
    id: 9,
    name: "Wireless Security",
    slug: "wireless-security",
    description: "Tools to test and secure WiFi networks, BLE, and other wireless protocols.",
    icon: "radio",
    color: "neon-blue",
    count: 1,
    tags: ["WiFi", "WPA", "Bluetooth"],
  },
  {
    id: 10,
    name: "Vulnerability Scanner",
    slug: "vulnerability-scanner",
    description: "Automated scanners that discover and report known vulnerabilities in systems.",
    icon: "search",
    color: "neon-green",
    count: 1,
    tags: ["CVE", "Compliance", "Audit"],
  },
  {
    id: 11,
    name: "Security OS",
    slug: "security-os",
    description: "Linux distributions pre-packaged with hundreds of security tools ready to use.",
    icon: "terminal",
    color: "neon-purple",
    count: 2,
    tags: ["Kali", "Parrot", "Live Boot"],
  },
  {
    id: 12,
    name: "Cryptography",
    slug: "cryptography",
    description: "Encryption, hashing, PKI tools, and crypto analysis frameworks.",
    icon: "key",
    color: "neon-pink",
    count: 0,
    tags: ["Encryption", "PKI", "Hashing"],
  },
];

export const getCategoryBySlug = (slug) =>
  CATEGORIES.find((c) => c.slug === slug);
