// Real cybersecurity tools database — used across all pages
export const TOOLS = [
  {
    id: 1,
    name: "Nmap",
    slug: "nmap",
    description: "The world's most popular network scanner. Used by network admins and penetration testers to discover hosts, open ports, and running services across networks of any size.",
    longDescription: "Nmap (Network Mapper) is a free and open-source network discovery and security auditing tool. It uses raw IP packets to determine what hosts are available, what services (application name and version) those hosts are offering, what operating systems they are running, what type of packet filters/firewalls are in use, and dozens of other characteristics. It is commonly used for network inventory, managing service upgrade schedules, and monitoring host or service uptime.",
    category: "Network Security",
    platform: ["Linux", "Windows", "macOS"],
    license: "GPL-2.0",
    openSource: true,
    free: true,
    website: "https://nmap.org",
    github: "https://github.com/nmap/nmap",
    stars: 9800,
    difficulty: "Intermediate",
    language: "C/C++",
    tags: ["network", "port-scanner", "reconnaissance", "host-discovery", "nse"],
    featured: true,
    installation: {
      linux: "sudo apt install nmap",
      windows: "Download the Nmap installer from https://nmap.org/download.html",
      macos: "brew install nmap",
    },
    features: ["Host Discovery", "Port Scanning", "Service Version Detection", "OS Detection", "Scripting Engine (NSE)"],
    alternatives: ["masscan", "rustscan", "zmap"],
  },
  {
    id: 2,
    name: "Metasploit Framework",
    slug: "metasploit",
    description: "The world's most used penetration testing framework. Contains hundreds of exploits, payloads, and auxiliary modules for ethical hacking and security research.",
    longDescription: "Metasploit is a widely used cybersecurity framework that enables security professionals to find security vulnerabilities, build exploit code, and test vulnerabilities in controlled environments. It simplifies the process of performing complex penetration testing tasks through an extensive library of exploits and tools.",
    category: "Penetration Testing",
    platform: ["Linux", "Windows", "macOS"],
    license: "BSD-3-Clause",
    openSource: true,
    free: true,
    website: "https://www.metasploit.com",
    github: "https://github.com/rapid7/metasploit-framework",
    stars: 34000,
    difficulty: "Advanced",
    language: "Ruby",
    tags: ["exploitation", "penetration-testing", "payloads", "post-exploitation", "meterpreter"],
    featured: true,
    installation: {
      linux: "curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb | sudo sh",
      windows: "Download the Windows Installer from metasploit.com",
      macos: "brew install metasploit",
    },
    features: ["500+ Exploits", "Meterpreter Shell", "Post-Exploitation Modules", "Payload Generation", "Database Integration"],
    alternatives: ["Cobalt Strike", "Empire", "Sliver"],
  },
  {
    id: 3,
    name: "Burp Suite",
    slug: "burp-suite",
    description: "The leading web application security testing platform. Intercept, inspect, and modify HTTP/HTTPS traffic between your browser and target web applications.",
    longDescription: "Burp Suite is an integrated platform for performing security testing of web applications. Its various tools work seamlessly together to support the entire testing process, from initial mapping and analysis of an application's attack surface, through to finding and exploiting security vulnerabilities.",
    category: "Web Security",
    platform: ["Linux", "Windows", "macOS"],
    license: "Proprietary",
    openSource: false,
    free: false,
    website: "https://portswigger.net/burp",
    github: null,
    stars: null,
    difficulty: "Intermediate",
    language: "Java",
    tags: ["web", "proxy", "http", "scanner", "interceptor", "spider"],
    featured: true,
    installation: {
      linux: "Download the JAR file from portswigger.net/burp/releases",
      windows: "Download the Windows installer from portswigger.net/burp/releases",
      macos: "Download the macOS installer from portswigger.net/burp/releases",
    },
    features: ["HTTP Interception Proxy", "Web Application Scanner", "Intruder (Brute Force)", "Repeater", "Decoder & Comparer"],
    alternatives: ["OWASP ZAP", "Mitmproxy", "Caido"],
  },
  {
    id: 4,
    name: "Wireshark",
    slug: "wireshark",
    description: "The world's foremost network protocol analyzer. Capture and interactively browse the traffic running on a computer network in incredible detail.",
    longDescription: "Wireshark is the world's most popular network protocol analyzer. It lets you see what's happening on your network at a microscopic level, and is the de facto standard across many commercial and non-profit enterprises, government agencies, and educational institutions.",
    category: "Network Security",
    platform: ["Linux", "Windows", "macOS"],
    license: "GPL-2.0",
    openSource: true,
    free: true,
    website: "https://www.wireshark.org",
    github: "https://github.com/wireshark/wireshark",
    stars: 7100,
    difficulty: "Beginner",
    language: "C",
    tags: ["network", "packet-capture", "protocol-analysis", "forensics", "pcap"],
    featured: true,
    installation: {
      linux: "sudo apt install wireshark",
      windows: "Download from wireshark.org",
      macos: "brew install --cask wireshark",
    },
    features: ["Live Packet Capture", "Deep Protocol Inspection", "Offline Analysis", "Display Filters", "Export to PCAP"],
    alternatives: ["tcpdump", "tshark", "NetworkMiner"],
  },
  {
    id: 5,
    name: "Hashcat",
    slug: "hashcat",
    description: "The world's fastest and most advanced password recovery tool. Supports hundreds of hashing algorithms and attack modes using GPU acceleration.",
    longDescription: "Hashcat is the world's fastest and most advanced password recovery utility, supporting five unique modes of attack for over 350 highly optimized hashing algorithms. It is capable of cracking hashes from WPA/WPA2, MD5, SHA-1, bcrypt, and many more.",
    category: "Password Cracking",
    platform: ["Linux", "Windows", "macOS"],
    license: "MIT",
    openSource: true,
    free: true,
    website: "https://hashcat.net",
    github: "https://github.com/hashcat/hashcat",
    stars: 21000,
    difficulty: "Advanced",
    language: "C",
    tags: ["password", "hash-cracking", "gpu", "brute-force", "dictionary"],
    featured: false,
    installation: {
      linux: "sudo apt install hashcat",
      windows: "Download from hashcat.net",
      macos: "brew install hashcat",
    },
    features: ["GPU Acceleration", "350+ Hash Algorithms", "Dictionary Attack", "Brute-Force", "Rule-Based Attack"],
    alternatives: ["John the Ripper", "Ophcrack", "Hydra"],
  },
  {
    id: 6,
    name: "John the Ripper",
    slug: "john-the-ripper",
    description: "A fast password cracker, currently available for many Unix-based systems, Windows, DOS and OpenVMS. Its primary purpose is to detect weak Unix passwords.",
    longDescription: "John the Ripper is a free and open-source password security auditing and password recovery tool available for many operating systems. It is designed to detect weak Unix passwords, but also supports Windows LM hashes and Kerberos AFS passwords.",
    category: "Password Cracking",
    platform: ["Linux", "Windows", "macOS"],
    license: "GPL-2.0",
    openSource: true,
    free: true,
    website: "https://www.openwall.com/john/",
    github: "https://github.com/openwall/john",
    stars: 9400,
    difficulty: "Intermediate",
    language: "C",
    tags: ["password", "hash", "unix", "wordlist", "crack"],
    featured: false,
    installation: {
      linux: "sudo apt install john",
      windows: "Download from openwall.com/john",
      macos: "brew install john",
    },
    features: ["Auto Hash Detection", "Wordlist Mode", "Incremental Mode", "External Mode", "Multiple Cipher Support"],
    alternatives: ["Hashcat", "Hydra", "Medusa"],
  },
  {
    id: 7,
    name: "SQLMap",
    slug: "sqlmap",
    description: "An open-source penetration testing tool that automates the detection and exploitation of SQL injection vulnerabilities and database takeovers.",
    longDescription: "SQLMap is an open-source penetration testing tool that automates the process of detecting and exploiting SQL injection flaws and taking over of database servers. It comes with a powerful detection engine, many niche features for the ultimate penetration tester, and a broad range of switches including database fingerprinting, data fetching, and more.",
    category: "Web Security",
    platform: ["Linux", "Windows", "macOS"],
    license: "GPL-2.0",
    openSource: true,
    free: true,
    website: "https://sqlmap.org",
    github: "https://github.com/sqlmapproject/sqlmap",
    stars: 32000,
    difficulty: "Intermediate",
    language: "Python",
    tags: ["sql-injection", "web", "database", "exploitation", "automation"],
    featured: true,
    installation: {
      linux: "sudo apt install sqlmap",
      windows: "pip install sqlmap or download from sqlmap.org",
      macos: "pip install sqlmap",
    },
    features: ["Auto SQL Injection Detection", "Database Fingerprinting", "Data Extraction", "OS Shell Access", "Multiple DB Support"],
    alternatives: ["Havij", "BBQSQL", "jSQL Injection"],
  },
  {
    id: 8,
    name: "Aircrack-ng",
    slug: "aircrack-ng",
    description: "A complete suite of tools to assess WiFi network security. Focuses on monitoring, attacking, testing and cracking WEP, WPA and WPA2 networks.",
    longDescription: "Aircrack-ng is a complete suite of tools to assess WiFi network security. It focuses on different areas of WiFi security: Monitoring (Packet Capture), Attacking (Replay attacks, deauthentication, fake access points), Testing (Checking WiFi cards and driver capabilities), and Cracking (WEP and WPA PSK).",
    category: "Wireless Security",
    platform: ["Linux", "Windows", "macOS"],
    license: "GPL-2.0",
    openSource: true,
    free: true,
    website: "https://www.aircrack-ng.org",
    github: "https://github.com/aircrack-ng/aircrack-ng",
    stars: 5000,
    difficulty: "Advanced",
    language: "C",
    tags: ["wifi", "wireless", "wpa", "crack", "deauth", "monitor-mode"],
    featured: false,
    installation: {
      linux: "sudo apt install aircrack-ng",
      windows: "Download from aircrack-ng.org",
      macos: "brew install aircrack-ng",
    },
    features: ["WEP/WPA/WPA2 Cracking", "Packet Capture", "Deauthentication Attacks", "Fake AP Creation", "Replay Attacks"],
    alternatives: ["Kismet", "Wifite", "WiFi-Pumpkin"],
  },
  {
    id: 9,
    name: "OWASP ZAP",
    slug: "owasp-zap",
    description: "The world's most widely used web app security scanner. Free, open-source, maintained by OWASP. Perfect for automated security testing in CI/CD pipelines.",
    longDescription: "Zed Attack Proxy (ZAP) is the world's most widely used web app security scanner. It is free, open source, and is actively maintained by a dedicated international team of volunteers. ZAP is ideal for developers, testers, and security professionals to test web applications for vulnerabilities.",
    category: "Web Security",
    platform: ["Linux", "Windows", "macOS"],
    license: "Apache-2.0",
    openSource: true,
    free: true,
    website: "https://www.zaproxy.org",
    github: "https://github.com/zaproxy/zaproxy",
    stars: 12000,
    difficulty: "Beginner",
    language: "Java",
    tags: ["web", "scanner", "owasp", "proxy", "automation", "ci-cd"],
    featured: false,
    installation: {
      linux: "sudo snap install zaproxy --classic",
      windows: "Download installer from zaproxy.org",
      macos: "brew install --cask owasp-zap",
    },
    features: ["Active & Passive Scanning", "HTTP Proxy", "Spider/Crawler", "REST API", "CI/CD Integration"],
    alternatives: ["Burp Suite", "Nikto", "Acunetix"],
  },
  {
    id: 10,
    name: "Nikto",
    slug: "nikto",
    description: "An open-source web server scanner that performs comprehensive tests against web servers for multiple items including over 6700 dangerous files and programs.",
    longDescription: "Nikto is an open source web server scanner which performs comprehensive tests against web servers for multiple items, including over 6700 potentially dangerous files/CGIs, checks for outdated versions of over 1250 servers, and version specific problems on over 270 servers.",
    category: "Web Security",
    platform: ["Linux", "Windows", "macOS"],
    license: "GPL-2.0",
    openSource: true,
    free: true,
    website: "https://cirt.net/Nikto2",
    github: "https://github.com/sullo/nikto",
    stars: 8500,
    difficulty: "Beginner",
    language: "Perl",
    tags: ["web", "scanner", "cgi", "server", "vulnerability"],
    featured: false,
    installation: {
      linux: "sudo apt install nikto",
      windows: "Requires Perl runtime, then clone from GitHub",
      macos: "brew install nikto",
    },
    features: ["6700+ Vulnerability Checks", "SSL/HTTPS Support", "Proxy Support", "Host Authentication", "Report Generation"],
    alternatives: ["OWASP ZAP", "Arachni", "W3af"],
  },
  {
    id: 11,
    name: "Maltego",
    slug: "maltego",
    description: "A powerful OSINT and graphical link analysis tool. Visualize relationships between people, companies, websites, domains, and online infrastructure.",
    longDescription: "Maltego is a comprehensive tool for graphical link analyses that offers real-time data mining and information gathering, as well as the representation of this information on a node-based graph, making patterns and multiple order connections between said information easily identifiable.",
    category: "OSINT",
    platform: ["Linux", "Windows", "macOS"],
    license: "Proprietary",
    openSource: false,
    free: false,
    website: "https://www.maltego.com",
    github: null,
    stars: null,
    difficulty: "Intermediate",
    language: "Java",
    tags: ["osint", "graph", "link-analysis", "reconnaissance", "social-engineering"],
    featured: false,
    installation: {
      linux: "Download from maltego.com",
      windows: "Download from maltego.com",
      macos: "Download from maltego.com",
    },
    features: ["Graph Visualization", "1000+ Transforms", "Social Network Analysis", "Domain/IP Mapping", "Email Reconnaissance"],
    alternatives: ["theHarvester", "Recon-ng", "SpiderFoot"],
  },
  {
    id: 12,
    name: "theHarvester",
    slug: "theharvester",
    description: "A simple yet effective OSINT tool designed to gather emails, subdomains, hosts, employee names, and open ports from different public sources.",
    longDescription: "theHarvester is a simple to use, yet powerful tool designed to be used during the reconnaissance stage of a security test or ethical hacking exercise. It performs open source intelligence (OSINT) by scraping multiple public data sources to enumerate email addresses, names, subdomains, IPs, and URLs belonging to a target.",
    category: "OSINT",
    platform: ["Linux", "Windows", "macOS"],
    license: "GPL-2.0",
    openSource: true,
    free: true,
    website: "https://github.com/laramies/theHarvester",
    github: "https://github.com/laramies/theHarvester",
    stars: 11000,
    difficulty: "Beginner",
    language: "Python",
    tags: ["osint", "email", "subdomain", "reconnaissance", "passive"],
    featured: false,
    installation: {
      linux: "sudo apt install theharvester",
      windows: "pip install theHarvester",
      macos: "pip install theHarvester",
    },
    features: ["Email Harvesting", "Subdomain Enumeration", "Multiple Data Sources", "Virtual Host Discovery", "Shodan Integration"],
    alternatives: ["Maltego", "Recon-ng", "Amass"],
  },
  {
    id: 13,
    name: "Ghidra",
    slug: "ghidra",
    description: "NSA's open-source software reverse engineering framework. Analyze compiled code and understand binary applications across various processors and environments.",
    longDescription: "Ghidra is a software reverse engineering (SRE) framework developed by NSA's Research Directorate. The framework includes a suite of full-featured, high-end software analysis tools that enable users to analyze compiled code on a variety of platforms including Windows, macOS, and Linux.",
    category: "Reverse Engineering",
    platform: ["Linux", "Windows", "macOS"],
    license: "Apache-2.0",
    openSource: true,
    free: true,
    website: "https://ghidra-sre.org",
    github: "https://github.com/NationalSecurityAgency/ghidra",
    stars: 52000,
    difficulty: "Advanced",
    language: "Java",
    tags: ["reverse-engineering", "disassembler", "decompiler", "binary", "malware-analysis", "nsa"],
    featured: true,
    installation: {
      linux: "Download from ghidra-sre.org, extract and run ghidraRun",
      windows: "Download from ghidra-sre.org, run ghidraRun.bat",
      macos: "Download from ghidra-sre.org, run ghidraRun",
    },
    features: ["Disassembler", "Decompiler", "Code Browser", "Script Support (Java/Python)", "Version Tracking"],
    alternatives: ["IDA Pro", "Binary Ninja", "Radare2"],
  },
  {
    id: 14,
    name: "Volatility",
    slug: "volatility",
    description: "The industry-standard memory forensics framework. Analyze RAM dumps to extract digital artifacts from Windows, Linux, macOS, and Android systems.",
    longDescription: "Volatility is an open source memory forensics framework for incident response and malware analysis. Written in Python, it is supported on all major platforms. Volatility supports memory images from Windows, Linux, macOS, and Android operating systems.",
    category: "Digital Forensics",
    platform: ["Linux", "Windows", "macOS"],
    license: "GPL-2.0",
    openSource: true,
    free: true,
    website: "https://www.volatilityfoundation.org",
    github: "https://github.com/volatilityfoundation/volatility3",
    stars: 7600,
    difficulty: "Advanced",
    language: "Python",
    tags: ["memory-forensics", "ram", "incident-response", "malware", "artifacts"],
    featured: false,
    installation: {
      linux: "pip install volatility3",
      windows: "pip install volatility3",
      macos: "pip install volatility3",
    },
    features: ["Process Analysis", "Network Connections", "Registry Analysis", "Malware Detection", "Timeline Generation"],
    alternatives: ["Rekall", "MemProcFS", "Redline"],
  },
  {
    id: 15,
    name: "Autopsy",
    slug: "autopsy",
    description: "A digital forensics platform and GUI for The Sleuth Kit. Used by law enforcement and corporate examiners to investigate hard drives and smartphones.",
    longDescription: "Autopsy is the premier open source forensics platform. It is used by thousands of law enforcement agencies, military, and corporate examiners to investigate what happened on a computer. It runs modules to analyze volume and file system data and present the results in an intuitive interface.",
    category: "Digital Forensics",
    platform: ["Linux", "Windows", "macOS"],
    license: "Apache-2.0",
    openSource: true,
    free: true,
    website: "https://www.autopsy.com",
    github: "https://github.com/sleuthkit/autopsy",
    stars: 2600,
    difficulty: "Intermediate",
    language: "Java",
    tags: ["forensics", "disk-imaging", "evidence", "timeline", "artifacts"],
    featured: false,
    installation: {
      linux: "Download DEB/RPM from autopsy.com",
      windows: "Download installer from autopsy.com",
      macos: "Download from autopsy.com",
    },
    features: ["Timeline Analysis", "Keyword Search", "Web Artifact Recovery", "Email Analysis", "Hash Filtering"],
    alternatives: ["Encase", "FTK", "Cellebrite"],
  },
  {
    id: 16,
    name: "OpenVAS",
    slug: "openvas",
    description: "A full-featured, open-source vulnerability scanner. Perform comprehensive vulnerability testing against servers and network devices, with 100,000+ NVT checks.",
    longDescription: "OpenVAS (Open Vulnerability Assessment System) is a framework of several services and tools offering a comprehensive and powerful vulnerability scanning and vulnerability management solution. It runs in the Greenbone Vulnerability Management framework.",
    category: "Vulnerability Scanner",
    platform: ["Linux"],
    license: "GPL-2.0",
    openSource: true,
    free: true,
    website: "https://openvas.org",
    github: "https://github.com/greenbone/openvas-scanner",
    stars: 3500,
    difficulty: "Intermediate",
    language: "C",
    tags: ["vulnerability", "scanner", "network", "compliance", "nvt"],
    featured: false,
    installation: {
      linux: "sudo apt install openvas && sudo gvm-setup",
      windows: "Not natively supported — run via Docker",
      macos: "Run via Docker",
    },
    features: ["100,000+ NVT Checks", "Authenticated Scanning", "Compliance Checks", "Report Generation", "API Access"],
    alternatives: ["Nessus", "Nexpose", "Qualys"],
  },
  {
    id: 17,
    name: "Hydra",
    slug: "hydra",
    description: "A fast and flexible online password cracker that supports numerous protocols including SMB, HTTP, FTP, SSH, RDP, and more. Essential for brute-force testing.",
    longDescription: "Hydra is a parallelized login cracker which supports numerous protocols to attack. It is very fast and flexible, and new modules are easy to add. This tool makes it possible for researchers and security consultants to show how easy it would be to gain unauthorized access to a system remotely.",
    category: "Password Cracking",
    platform: ["Linux", "Windows", "macOS"],
    license: "GPL-3.0",
    openSource: true,
    free: true,
    website: "https://github.com/vanhauser-thc/thc-hydra",
    github: "https://github.com/vanhauser-thc/thc-hydra",
    stars: 10000,
    difficulty: "Intermediate",
    language: "C",
    tags: ["brute-force", "login", "ssh", "ftp", "http", "rdp", "smb"],
    featured: false,
    installation: {
      linux: "sudo apt install hydra",
      windows: "Build from source on GitHub",
      macos: "brew install hydra",
    },
    features: ["50+ Protocol Support", "Multi-Threading", "Proxy Support", "IPv6 Support", "Custom Module Creation"],
    alternatives: ["Medusa", "Patator", "Ncrack"],
  },
  {
    id: 18,
    name: "Kali Linux",
    slug: "kali-linux",
    description: "The world's most advanced penetration testing Linux distribution. Pre-loaded with 600+ security tools. The gold standard for ethical hackers and security professionals.",
    longDescription: "Kali Linux is a Debian-based Linux distribution aimed at advanced penetration testing and security auditing. Kali contains several hundred tools targeted toward various information security tasks, such as penetration testing, security research, computer forensics, and reverse engineering.",
    category: "Security OS",
    platform: ["Linux"],
    license: "GPL-2.0",
    openSource: true,
    free: true,
    website: "https://www.kali.org",
    github: "https://github.com/offensive-security/kali-linux",
    stars: 6200,
    difficulty: "Intermediate",
    language: "Bash",
    tags: ["os", "linux", "distribution", "penetration-testing", "kali"],
    featured: true,
    installation: {
      linux: "Download ISO from kali.org, or install via WSL2 on Windows",
      windows: "Install Kali via WSL2: wsl --install kali-linux",
      macos: "Run in UTM/VirtualBox VM",
    },
    features: ["600+ Pre-installed Tools", "Live Boot", "ARM Support", "Undercover Mode", "Rolling Release"],
    alternatives: ["Parrot OS", "BlackArch", "Tails"],
  },
  {
    id: 19,
    name: "Parrot OS",
    slug: "parrot-os",
    description: "A security-focused Debian-based Linux distribution. Comes with a complete arsenal of security tools, privacy features, and a lightweight MATE desktop.",
    longDescription: "Parrot OS is a Debian-based Linux distribution designed for security and privacy. It is a lightweight alternative to Kali Linux and features the MATE desktop environment. It comes pre-loaded with security tools and is optimized for penetration testing, privacy, and digital forensics.",
    category: "Security OS",
    platform: ["Linux"],
    license: "GPL-2.0",
    openSource: true,
    free: true,
    website: "https://www.parrotsec.org",
    github: "https://github.com/ParrotSec/parrot-core",
    stars: 1300,
    difficulty: "Beginner",
    language: "Bash",
    tags: ["os", "linux", "privacy", "security", "lightweight"],
    featured: false,
    installation: {
      linux: "Download ISO from parrotsec.org",
      windows: "Run in VirtualBox or VMware",
      macos: "Run in UTM VM",
    },
    features: ["Lightweight MATE Desktop", "Privacy Tools Pre-installed", "Developer Edition Available", "Rolling Release", "Sandbox Mode"],
    alternatives: ["Kali Linux", "BlackArch", "Tails"],
  },
  {
    id: 20,
    name: "Cuckoo Sandbox",
    slug: "cuckoo-sandbox",
    description: "An automated open-source malware analysis system. Submit suspicious files and URLs to analyze behavior in an isolated environment without risk.",
    longDescription: "Cuckoo Sandbox is an advanced open-source automated malware analysis system. Submit any suspicious file to it and in a few seconds Cuckoo will provide some detailed results outlining what such file did when executed inside an isolated environment.",
    category: "Malware Analysis",
    platform: ["Linux"],
    license: "GPL-3.0",
    openSource: true,
    free: true,
    website: "https://cuckoosandbox.org",
    github: "https://github.com/cuckoosandbox/cuckoo",
    stars: 5600,
    difficulty: "Advanced",
    language: "Python",
    tags: ["malware", "sandbox", "analysis", "behavior", "automated"],
    featured: false,
    installation: {
      linux: "pip install cuckoo && cuckoo setup",
      windows: "Not natively supported",
      macos: "Not supported",
    },
    features: ["Behavioral Analysis", "Network Traffic Monitoring", "Memory Analysis", "File Tracking", "Report Generation"],
    alternatives: ["Joe Sandbox", "Any.run", "Hybrid Analysis"],
  },
  {
    id: 21,
    name: "YARA",
    slug: "yara",
    description: "The pattern matching swiss knife for malware researchers. Write rules to identify and classify malware samples based on textual or binary patterns.",
    longDescription: "YARA is a tool aimed at helping malware researchers to identify and classify malware samples. With YARA you can create descriptions of malware families based on textual or binary patterns. Each description, aka rule, consists of a set of strings and a Boolean expression which determine its logic.",
    category: "Malware Analysis",
    platform: ["Linux", "Windows", "macOS"],
    license: "BSD-3-Clause",
    openSource: true,
    free: true,
    website: "https://virustotal.github.io/yara/",
    github: "https://github.com/VirusTotal/yara",
    stars: 8100,
    difficulty: "Intermediate",
    language: "C",
    tags: ["malware", "pattern-matching", "signatures", "detection", "virustotal"],
    featured: false,
    installation: {
      linux: "sudo apt install yara",
      windows: "Download from GitHub releases",
      macos: "brew install yara",
    },
    features: ["Custom Rule Creation", "String & Binary Matching", "Module Support", "Python Bindings", "PE Module"],
    alternatives: ["SIGMA", "Snort Rules", "Zeek Scripts"],
  },
  {
    id: 22,
    name: "Shodan",
    slug: "shodan",
    description: "The world's first search engine for internet-connected devices. Discover servers, routers, IoT devices, webcams, and industrial systems exposed to the internet.",
    longDescription: "Shodan is the world's first search engine for internet-connected devices. It allows you to explore the internet of things, find specific types of computer devices using a variety of filters, and discover information about misconfigured servers and network devices exposed to the public internet.",
    category: "OSINT",
    platform: ["Linux", "Windows", "macOS"],
    license: "Proprietary",
    openSource: false,
    free: false,
    website: "https://www.shodan.io",
    github: null,
    stars: null,
    difficulty: "Beginner",
    language: "Python",
    tags: ["osint", "iot", "search-engine", "reconnaissance", "internet-scanning"],
    featured: true,
    installation: {
      linux: "pip install shodan (CLI client)",
      windows: "pip install shodan",
      macos: "pip install shodan",
    },
    features: ["IoT Device Search", "Vulnerability Search", "API Access", "Network Maps", "Exploit Search"],
    alternatives: ["Censys", "ZoomEye", "FOFA"],
  },
  {
    id: 23,
    name: "Snort",
    slug: "snort",
    description: "The world's most widely deployed intrusion detection and prevention system. Perform real-time traffic analysis and packet logging with rule-based detection.",
    longDescription: "Snort is the foremost Open Source Intrusion Prevention System (IPS) in the world. Snort IPS uses a series of rules that help define malicious network activity and uses those rules to find packets that match against them and generates alerts for users.",
    category: "Network Security",
    platform: ["Linux", "Windows"],
    license: "GPL-2.0",
    openSource: true,
    free: true,
    website: "https://www.snort.org",
    github: "https://github.com/snort3/snort3",
    stars: 2000,
    difficulty: "Advanced",
    language: "C++",
    tags: ["ids", "ips", "network", "detection", "rules", "packets"],
    featured: false,
    installation: {
      linux: "sudo apt install snort",
      windows: "Download installer from snort.org",
      macos: "Build from source",
    },
    features: ["Real-Time Traffic Analysis", "Packet Logging", "Protocol Analysis", "Content Matching", "Rule-Based Detection"],
    alternatives: ["Suricata", "Zeek", "OSSEC"],
  },
  {
    id: 24,
    name: "Recon-ng",
    slug: "recon-ng",
    description: "A full-featured web reconnaissance framework with a powerful module system. Provides a powerful environment to conduct open source web-based reconnaissance quickly.",
    longDescription: "Recon-ng is a full-featured reconnaissance framework designed with the goal of providing a powerful environment to conduct open source, web-based reconnaissance quickly and thoroughly. The interface is similar to the Metasploit Framework with tab-complete support.",
    category: "OSINT",
    platform: ["Linux", "macOS"],
    license: "GPL-3.0",
    openSource: true,
    free: true,
    website: "https://github.com/lanmaster53/recon-ng",
    github: "https://github.com/lanmaster53/recon-ng",
    stars: 5400,
    difficulty: "Intermediate",
    language: "Python",
    tags: ["osint", "reconnaissance", "web", "framework", "modules"],
    featured: false,
    installation: {
      linux: "sudo apt install recon-ng",
      windows: "pip install recon-ng",
      macos: "pip install recon-ng",
    },
    features: ["Modular Architecture", "Database Storage", "Report Generation", "API Key Management", "Workspace Support"],
    alternatives: ["theHarvester", "Maltego", "SpiderFoot"],
  },
  {
    id: 25,
    name: "Mimikatz",
    slug: "mimikatz",
    description: "A post-exploitation tool to extract password hashes, plaintext passwords, Kerberos tickets, and other credentials directly from Windows memory.",
    longDescription: "Mimikatz is an open-source application that allows users to view and save authentication credentials like Kerberos tickets. It has become one of the most commonly used post-exploitation tools for credential harvesting on Windows environments.",
    category: "Penetration Testing",
    platform: ["Windows"],
    license: "CC-BY-4.0",
    openSource: true,
    free: true,
    website: "https://github.com/gentilkiwi/mimikatz",
    github: "https://github.com/gentilkiwi/mimikatz",
    stars: 19000,
    difficulty: "Advanced",
    language: "C",
    tags: ["windows", "credentials", "kerberos", "lsass", "post-exploitation", "pass-the-hash"],
    featured: false,
    installation: {
      linux: "Not available",
      windows: "Download from GitHub releases (run as Administrator)",
      macos: "Not available",
    },
    features: ["Credential Harvesting", "Pass-the-Hash", "Pass-the-Ticket", "Golden Ticket", "DCSync"],
    alternatives: ["LaZagne", "Impacket", "CrackMapExec"],
  },
];

// Get tool by slug
export const getToolBySlug = (slug) => TOOLS.find((t) => t.slug === slug);

// Get featured tools
export const getFeaturedTools = () => TOOLS.filter((t) => t.featured);

// Get tools by category
export const getToolsByCategory = (category) =>
  TOOLS.filter((t) => t.category === category);

// Get all unique categories from tools
export const getAllCategories = () => [...new Set(TOOLS.map((t) => t.category))];

// Get all unique platforms
export const getAllPlatforms = () => [
  ...new Set(TOOLS.flatMap((t) => t.platform)),
];

// Get all unique languages
export const getAllLanguages = () => [
  ...new Set(TOOLS.map((t) => t.language)),
];
